Data Cleaning

In [1]:
#Importing required Libraries
import pandas as pd
import ast
import hashlib
import os

file_path = "../data/raw/data_jobs.csv"

if not os.path.exists(file_path):
    file_path = "../data/raw/data_jobs_sample.csv"

df = pd.read_csv(file_path)

#Check top 5 rows
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.7 MB

In [3]:
#Basic Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df['job_via'] = df['job_via'].str.replace('via ', '')
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 262.5 MB

In [5]:
df.describe()

                  job_posted_date  salary_year_avg  salary_hour_avg
count                      785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860247    123286.274072        47.016598
min           2023-01-01 00:00:04     15000.000000         8.000000
25%           2023-03-20 10:05:48     90000.000000        27.500000
50%           2023-06-29 06:11:38    115000.000000        45.980000
75%           2023-09-27 01:01:16    150000.000000        61.159996
max           2023-12-31 23:59:58    960000.000000       391.000000
std                           NaN     48312.449482        21.890738

In [6]:
df.duplicated().sum()

np.int64(101)

In [7]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

Data Tranformation

In [8]:
import ast

#parsing job_skills column to change from string to list
def safe_parse(x):
    try:        
        return ast.literal_eval(x) if isinstance(x, str) else []
    except:        
        return ['PARSE_ERROR']
    
df['job_skills'] = df['job_skills'].apply(safe_parse)

#parsing job_type_skills column to change from string to dictionary of_list
def parse_dict(x):
    try:
        return ast.literal_eval(x) if isinstance(x, str) else {}
    except:
        return {'PARSE_ERROR'}
        
df['job_type_skills'] = df['job_type_skills'].apply(parse_dict)

In [9]:
import hashlib

#generate unique job_id
def generate_job_id(row):
    title_short = str(row['job_title_short']).strip().lower() if pd.notna(row['job_title_short']) else''
    title = str(row['job_title']).strip().lower() if pd.notna(row['job_title']) else ''
    company = str(row['company_name']).strip().lower() if pd.notna(row['company_name']) else ''
    job_location = str(row['job_location']).strip().lower() if pd.notna(row['job_location']) else ''
    search_location = str(row['search_location']).strip().lower() if pd.notna(row['search_location']) else ''
    job_date = str(row['job_posted_date']).strip().lower() if pd.notna(row['job_posted_date']) else ''
    #rate = str(row['salary_rate']).strip().lower() if pd.notna(row['salary_rate']) else ''
    #skills = str(row['job_skills']).strip().lower() if pd.notna(row['job_skills']) else ''
    
    text = f"{title_short}|{title}|{company}|{job_location}|{search_location}|{job_date}"
    
    return 'J-' + hashlib.md5(text.encode('utf-8')).hexdigest()[:12]

df['job_id'] = df.apply(generate_job_id, axis=1)

# Same job → same ID across datasets ✅
# Adding new data → no problem ✅
# Removing duplicates → IDs unchanged

In [10]:
df.loc[:5,'job_skills':'job_id']

,job_skills,job_type_skills,job_id
0,[],{},J-e02c886264ce
1,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",J-64833455be38
2,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",J-c8afb754b830
3,"[python, c++, java, matlab, aws, tensorflow, k...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",J-6b595ba75824
4,"[bash, python, oracle, aws, ansible, puppet, j...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",J-88bb30c3cf7d
5,"[python, sql, gcp]","{'cloud': ['gcp'], 'programming': ['python', '...",J-39b48817780e

In [11]:
df[df['job_id'].duplicated()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_id
8212,Data Analyst,Data analist,"Brussels, Belgium",LinkedIn Belgium,Full-time,False,Belgium,2023-10-30 13:25:04,True,False,Belgium,NaN,NaN,NaN,Connect Consulting,"[sql, azure]","{'cloud': ['azure'], 'programming': ['sql']}",J-dfc8d3c1b9b3
8688,Senior Data Analyst,Senior Data Analyst,"Santiago, Chile",BeBee Chile,Full-time,False,Chile,2023-03-01 13:33:11,True,False,Chile,NaN,NaN,NaN,Corp,"[sql, tableau]","{'analyst_tools': ['tableau'], 'programming': ...",J-142ad013ce66
13981,Data Engineer,Data engineer,Singapore,Indeed,Contractor,False,Singapore,2023-02-16 13:31:14,False,False,Singapore,NaN,NaN,NaN,U3 Infotech Pte Ltd.,"[python, scala, java, elasticsearch, redshift,...","{'cloud': ['redshift'], 'databases': ['elastic...",J-33fb5f8b15e6
14817,Data Analyst,Data analist,"Brussels, Belgium",LinkedIn Belgium,Full-time,False,Belgium,2023-10-30 13:25:04,False,False,Belgium,NaN,NaN,NaN,Connect Consulting,[],{},J-dfc8d3c1b9b3
16782,Data Engineer,Práctica Data Engineer,"Las Condes, Chile",Trabajo.org,Full-time,False,Chile,2023-02-25 13:56:15,True,False,Chile,NaN,NaN,NaN,Banco Bci,"[python, r, azure, power bi]","{'analyst_tools': ['power bi'], 'cloud': ['azu...",J-68790f93b704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784599,Data Engineer,Process Data Engineer,"Makati, Metro Manila, Philippines",Trabajo.org,Full-time,False,Philippines,2023-01-22 06:22:02,False,False,Philippines,NaN,NaN,NaN,Shell,[shell],{'programming': ['shell']},J-d1d9f7739fc9
784971,Senior Data Engineer,Senior Data Engineer,Singapore,LinkedIn,Full-time,False,Singapore,2023-01-06 06:42:32,False,False,Singapore,NaN,NaN,NaN,Michael Page,"[shell, python, r, aws, redshift, hadoop]","{'cloud': ['aws', 'redshift'], 'libraries': ['...",J-aa46c4bf1a97
785193,Data Analyst,Data Analyst,"Buenos Aires, Argentina","Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-10-14 07:07:44,True,False,Argentina,NaN,NaN,NaN,Emprego,"[sql, r]","{'programming': ['sql', 'r']}",J-adbc52a73041
785458,Software Engineer,Senior Software Engineer,"Helsinki, Finland",Trabajo.org,Full-time,False,Finland,2023-01-03 06:30:13,False,False,Finland,NaN,NaN,NaN,Canonical Group Ltd,"[go, c, c++, mongodb, mongodb, openstack, ubun...","{'cloud': ['openstack'], 'databases': ['mongod...",J-b5661381107a
785608,Software Engineer,Senior Software Engineer,"Buenos Aires, Argentina","Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-09-28 06:29:25,True,False,Argentina,NaN,NaN,NaN,Emprego,"[php, javascript, css, sass, sql, nosql, react...","{'libraries': ['react', 'graphql', 'kafka'], '...",J-cedce55a233a

In [12]:
merged_skills = df.groupby('job_id')['job_skills'].apply(
    lambda x: sorted(set(skill for sublist in x for skill in sublist))
)

merged_via = df.groupby('job_id')['job_via'].apply(
    lambda x: list(set(x))
)

merged_rate = df.groupby('job_id')['salary_rate'].apply(
    lambda x: next((v for v in x if pd.notna(v)), None)
)

In [13]:
from collections import defaultdict

merged_job_type_skills = {}

for job_id, group in df.groupby('job_id'):
    merged = defaultdict(set)
    
    for d in group['job_type_skills']:
        if isinstance(d, dict):
            for key, values in d.items():
                if isinstance(values, list):
                    merged[key].update(values)
    
    merged_job_type_skills[job_id] = {k: sorted(v) for k, v in merged.items()}

In [14]:
df['job_skills'] = df['job_id'].map(merged_skills)
df['job_via'] = df['job_id'].map(merged_via)
df['salary_rate'] = df['job_id'].map(merged_rate)
df['job_type_skills'] = df['job_id'].map(merged_job_type_skills)

In [15]:
df = df.drop_duplicates(subset='job_id')

In [16]:
df[df['job_id'].duplicated()]

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills, job_id]
Index: []