# Data Cleaning & Skills_df creation
This notebook focuses on loading raw file and it's cleaning along with creating a dedicated DataFrame for skills which will be used for different analysis in later notebooks.

## 1. Data Load and Cleaning

In [1]:
# Importing required Libraries
import pandas as pd
import ast
import hashlib
import os

# Decide which file to use (full raw file if available or sample file)
file_path = "../data/raw/data_jobs.csv"

if not os.path.exists(file_path):
    file_path = "../data/raw/data_jobs_sample.csv"

# Load chosen file
df = pd.read_csv(file_path)

# Check top 5 rows
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [2]:
# Check summary of raw data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.7 MB

In [3]:
# Check exact duplicates
df.duplicated().sum()

np.int64(101)

#### 1.1 Basic Data Cleaning

In [4]:
# Remove exact duplicate rows
df = df.drop_duplicates()

# Duplicate sum should be 0 now
df.duplicated().sum()

np.int64(0)

In [5]:
# Convert job_posted_date to datetime format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# Clean 'job_via' column by removing 'via ' prefix
df['job_via'] = df['job_via'].str.replace('via ', '')

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [6]:
# Statistical summary
df.describe()

                  job_posted_date  salary_year_avg  salary_hour_avg
count                      785640     22002.000000     10662.000000
mean   2023-06-25 15:57:23.961386    123287.786947        47.016598
min           2023-01-01 00:00:04     15000.000000         8.000000
25%           2023-03-20 10:04:42     90000.000000        27.500000
50%           2023-06-29 06:02:19    115000.000000        45.980000
75%           2023-09-27 01:00:12    150000.000000        61.159996
max           2023-12-31 23:59:58    960000.000000       391.000000
std                           NaN     48313.026222        21.890738

#### 1.2 Data Tranformation

In [7]:
import ast

# Parse String Columns

# Convert job_skills from string → list
def safe_parse(x):
    try:        
        return ast.literal_eval(x) if isinstance(x, str) else []
    except:
        # Mark rows where parsing fails        
        return ['PARSE_ERROR']
    
df['job_skills'] = df['job_skills'].apply(safe_parse)

# Convert job_type_skills from string → dictionary
def parse_dict(x):
    try:
        return ast.literal_eval(x) if isinstance(x, str) else {}
    except:
        return {'PARSE_ERROR'}
        
df['job_type_skills'] = df['job_type_skills'].apply(parse_dict)

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,[],{}
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"[python, c++, java, matlab, aws, tensorflow, k...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"[bash, python, oracle, aws, ansible, puppet, j...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [8]:
# Generate Unique Job ID
import hashlib

# Create a unique ID using key job attributes.
# Helps in deduplication and merging similar postings.

def generate_job_id(row):
    title_short = str(row['job_title_short']).strip().lower() if pd.notna(row['job_title_short']) else''
    title = str(row['job_title']).strip().lower() if pd.notna(row['job_title']) else ''
    company = str(row['company_name']).strip().lower() if pd.notna(row['company_name']) else ''
    job_location = str(row['job_location']).strip().lower() if pd.notna(row['job_location']) else ''
    search_location = str(row['search_location']).strip().lower() if pd.notna(row['search_location']) else ''
    job_date = str(row['job_posted_date']).strip().lower() if pd.notna(row['job_posted_date']) else ''

    # Combine fields into a single string
    text = f"{title_short}|{title}|{company}|{job_location}|{search_location}|{job_date}"
    
    # Generate hash-based ID
    return 'J-' + hashlib.md5(text.encode('utf-8')).hexdigest()[:12]

df['job_id'] = df.apply(generate_job_id, axis=1)

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_id
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,[],{},J-e02c886264ce
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",J-64833455be38
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",J-c8afb754b830
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"[python, c++, java, matlab, aws, tensorflow, k...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",J-6b595ba75824
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"[bash, python, oracle, aws, ansible, puppet, j...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",J-88bb30c3cf7d

In [9]:
# Check transformed columns
df.loc[:5,'job_skills':'job_id']

,job_skills,job_type_skills,job_id
0,[],{},J-e02c886264ce
1,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",J-64833455be38
2,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",J-c8afb754b830
3,"[python, c++, java, matlab, aws, tensorflow, k...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",J-6b595ba75824
4,"[bash, python, oracle, aws, ansible, puppet, j...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",J-88bb30c3cf7d
5,"[python, sql, gcp]","{'cloud': ['gcp'], 'programming': ['python', '...",J-39b48817780e

In [10]:
# Check for duplicate job_id
df[df['job_id'].duplicated()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_id
8212,Data Analyst,Data analist,"Brussels, Belgium",LinkedIn Belgium,Full-time,False,Belgium,2023-10-30 13:25:04,True,False,Belgium,NaN,NaN,NaN,Connect Consulting,"[sql, azure]","{'cloud': ['azure'], 'programming': ['sql']}",J-dfc8d3c1b9b3
8688,Senior Data Analyst,Senior Data Analyst,"Santiago, Chile",BeBee Chile,Full-time,False,Chile,2023-03-01 13:33:11,True,False,Chile,NaN,NaN,NaN,Corp,"[sql, tableau]","{'analyst_tools': ['tableau'], 'programming': ...",J-142ad013ce66
13981,Data Engineer,Data engineer,Singapore,Indeed,Contractor,False,Singapore,2023-02-16 13:31:14,False,False,Singapore,NaN,NaN,NaN,U3 Infotech Pte Ltd.,"[python, scala, java, elasticsearch, redshift,...","{'cloud': ['redshift'], 'databases': ['elastic...",J-33fb5f8b15e6
14817,Data Analyst,Data analist,"Brussels, Belgium",LinkedIn Belgium,Full-time,False,Belgium,2023-10-30 13:25:04,False,False,Belgium,NaN,NaN,NaN,Connect Consulting,[],{},J-dfc8d3c1b9b3
16782,Data Engineer,Práctica Data Engineer,"Las Condes, Chile",Trabajo.org,Full-time,False,Chile,2023-02-25 13:56:15,True,False,Chile,NaN,NaN,NaN,Banco Bci,"[python, r, azure, power bi]","{'analyst_tools': ['power bi'], 'cloud': ['azu...",J-68790f93b704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784599,Data Engineer,Process Data Engineer,"Makati, Metro Manila, Philippines",Trabajo.org,Full-time,False,Philippines,2023-01-22 06:22:02,False,False,Philippines,NaN,NaN,NaN,Shell,[shell],{'programming': ['shell']},J-d1d9f7739fc9
784971,Senior Data Engineer,Senior Data Engineer,Singapore,LinkedIn,Full-time,False,Singapore,2023-01-06 06:42:32,False,False,Singapore,NaN,NaN,NaN,Michael Page,"[shell, python, r, aws, redshift, hadoop]","{'cloud': ['aws', 'redshift'], 'libraries': ['...",J-aa46c4bf1a97
785193,Data Analyst,Data Analyst,"Buenos Aires, Argentina","Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-10-14 07:07:44,True,False,Argentina,NaN,NaN,NaN,Emprego,"[sql, r]","{'programming': ['sql', 'r']}",J-adbc52a73041
785458,Software Engineer,Senior Software Engineer,"Helsinki, Finland",Trabajo.org,Full-time,False,Finland,2023-01-03 06:30:13,False,False,Finland,NaN,NaN,NaN,Canonical Group Ltd,"[go, c, c++, mongodb, mongodb, openstack, ubun...","{'cloud': ['openstack'], 'databases': ['mongod...",J-b5661381107a
785608,Software Engineer,Senior Software Engineer,"Buenos Aires, Argentina","Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-09-28 06:29:25,True,False,Argentina,NaN,NaN,NaN,Emprego,"[php, javascript, css, sass, sql, nosql, react...","{'libraries': ['react', 'graphql', 'kafka'], '...",J-cedce55a233a

In [11]:
#Merge Duplicate Job Entries

# Merge job_skills → flatten and remove duplicates
merged_skills = df.groupby('job_id')['job_skills'].apply(
    lambda x: sorted(set(skill for sublist in x for skill in sublist))
)
merged_skills

job_id
J-00003f27f780                                 [javascript, looker]
J-00006a57515a                                         [powerpoint]
J-0000b86017e0    [azure, databricks, elasticsearch, gcp, powers...
J-0000b8ce547e                                 [azure, hadoop, sql]
J-0000c803aed4                                                   []
                                        ...
J-ffffb5ffe77c                [azure, power bi, python, r, tableau]
J-ffffc36ebcae    [aws, azure, cassandra, hadoop, java, kafka, m...
J-ffffd391171c                                     [snowflake, sql]
J-ffffd8497e0e                     [firebase, html, python, r, sql]
J-ffffe6b91d81                                                   []
Name: job_skills, Length: 784868, dtype: object

In [12]:
# Merge job_via → keep unique platforms
merged_via = df.groupby('job_id')['job_via'].apply(
    lambda x: list(set(x))
)
merged_via

job_id
J-00003f27f780         [Indeed]
J-00006a57515a          [BeBee]
J-0000b86017e0       [LinkedIn]
J-0000b8ce547e       [LinkedIn]
J-0000c803aed4       [Sercanto]
                      ...
J-ffffb5ffe77c          [BeBee]
J-ffffc36ebcae       [Snagajob]
J-ffffd391171c       [Tarta.ai]
J-ffffd8497e0e    [Recruit.net]
J-ffffe6b91d81          [BeBee]
Name: job_via, Length: 784868, dtype: object

In [13]:
# Merge salary_rate → take first non-null value
merged_rate = df.groupby('job_id')['salary_rate'].apply(
    lambda x: next((v for v in x if pd.notna(v)), None)
)

merged_rate

job_id
J-00003f27f780    NaN
J-00006a57515a    NaN
J-0000b86017e0    NaN
J-0000b8ce547e    NaN
J-0000c803aed4    NaN
                 ...
J-ffffb5ffe77c    NaN
J-ffffc36ebcae    NaN
J-ffffd391171c    NaN
J-ffffd8497e0e    NaN
J-ffffe6b91d81    NaN
Name: salary_rate, Length: 784868, dtype: str

In [14]:
# Merge job_type_skills → combine dictionaries and deduplicate values

from collections import defaultdict

merged_job_type_skills = {}

for job_id, group in df.groupby('job_id'):
    merged = defaultdict(set)
    
    for d in group['job_type_skills']:
        if isinstance(d, dict):
            for key, values in d.items():
                if isinstance(values, list):
                    merged[key].update(values)
    
    # Convert sets → sorted lists
    merged_job_type_skills[job_id] = {k: sorted(v) for k, v in merged.items()}

In [15]:
merged_job_type_skills

{'J-00003f27f780': {'analyst_tools': ['looker'],
  'programming': ['javascript']},
 'J-00006a57515a': {'analyst_tools': ['powerpoint']},
 'J-0000b86017e0': {'cloud': ['azure', 'databricks', 'gcp'],
  'databases': ['elasticsearch'],
  'other': ['terraform'],
  'programming': ['powershell', 'python', 'sql']},
 'J-0000b8ce547e': {'cloud': ['azure'],
  'libraries': ['hadoop'],
  'programming': ['sql']},
 'J-0000c803aed4': {},
 'J-0000d1bf104f': {'analyst_tools': ['excel', 'power bi'],
  'programming': ['crystal', 'javascript', 'sql', 'vba']},
 'J-0000e6537d7c': {'analyst_tools': ['qlik', 'tableau'],
  'programming': ['python', 'sql']},
 'J-0000ecefeca4': {'analyst_tools': ['power bi', 'tableau'],
  'libraries': ['tensorflow'],
  'programming': ['python', 'r', 'sql']},
 'J-0000fdac5f7e': {'analyst_tools': ['alteryx'],
  'cloud': ['aws', 'azure', 'redshift', 'snowflake'],
  'databases': ['mongodb'],
  'libraries': ['hadoop', 'spark'],
  'programming': ['c#', 'java', 'mongodb', 'python', 'r', 'sql']},
 'J-000100ab1fdc': {},
 'J-00010c86a4f0': {'libraries': ['numpy', 'pandas', 'tensorflow'],
  'programming': ['python', 'sql']},
 'J-00011a98a20d': {'analyst_tools': ['excel',
   'power bi',
   'powerpoint',
   'sharepoint',
   'word'],
  'libraries': ['hadoop'],
  'programming': ['python', 'r', 'sql', 'vba']},
 'J-00013741702d': {'libraries': ['ggplot2'],
  'os': ['linux', 'windows'],
  'other': ['git', 'github'],
  'programming': ['python', 'r', 'sql'],
  'webframeworks': ['vue']},
 'J-00013e2a1d76': {},
 'J-00014130cc1f': {'analyst_tools': ['excel', 'power bi', 'qlik', 'tableau'],
  'programming': ['go', 'python', 'r']},
 'J-000149576d5c': {'cloud': ['aws']},
 'J-0001887e611d': {'analyst_tools': ['power bi'],
  'cloud': ['azure', 'databricks'],
  'libraries': ['airflow',
   'hadoop',
   'jupyter',
   'kafka',
   'numpy',
   'pandas',
   'plotly',
   'spark'],
  'other': ['flow'],
  'programming': ['nosql', 'python', 'sql']},
 'J-000188f59b2c': {'async': ['confluence', 'jira'],
  'libraries': ['keras', 'pytorch', 'selenium'],
  'other': ['github', 'jenkins'],
  'programming': ['java', 'python', 'r']},
 'J-000189196170': {'analyst_tools': ['excel'],
  'cloud': ['azure'],
  'other': ['git'],
  'programming': ['python']},
 'J-00018b6687ce': {'analyst_tools': ['dax', 'power bi'],
  'cloud': ['snowflake'],
  'programming': ['python', 'r', 'sql']},
 'J-0001a3a61ab7': {'databases': ['mysql', 'redis'],
  'os': ['linux'],
  'other': ['docker', 'git'],
  'programming': ['python'],
  'webframeworks': ['django']},
 'J-0001a3f796a0': {'libraries': ['jupyter'], 'programming': ['python']},
 'J-0001b38be8a4': {'analyst_tools': ['excel', 'powerpoint', 'word']},
 'J-0001ca89bc0c': {},
 'J-0001d61778d4': {'analyst_tools': ['tableau'],
  'libraries': ['matplotlib'],
  'programming': ['c++', 'java', 'python', 'r', 'scala', 'sql']},
 'J-0001e0cf7a0f': {},
 'J-0001f42001da': {'libraries': ['pyspark', 'spark'],
  'programming': ['python', 'scala'],
  'analyst_tools': ['power bi'],
  'cloud': ['aws']},
 'J-00021897da94': {'libraries': ['keras', 'tensorflow'],
  'programming': ['go', 'python', 'sql']},
 'J-000224de33aa': {'analyst_tools': ['power bi', 'sap', 'tableau'],
  'cloud': ['azure', 'snowflake'],
  'databases': ['sql server'],
  'libraries': ['kafka'],
  'other': ['git'],
  'programming': ['sql']},
 'J-00023f280d24': {'other': ['git'],
  'programming': ['java', 'python', 'scala', 'sql']},
 'J-00025407d796': {'analyst_tools': ['excel', 'sas', 'spss', 'tableau'],
  'cloud': ['oracle'],
  'programming': ['matlab', 'python', 'r', 'sas', 'sql', 'visual basic']},
 'J-000254e372ee': {'analyst_tools': ['excel',
   'power bi',
   'ssis',
   'ssrs',
   'tableau'],
  'programming': ['sql']},
 'J-000267cc0173': {'analyst_tools': ['looker', 'tableau'],
  'cloud': ['aws', 'bigquery', 'redshift', 'snowflake'],
  'libraries': ['airflow'],
  'other': ['terraform'],
  'programming': ['python', 'sql'],
  'sync': ['unify']},
 'J-00027160eb50': {'cloud': ['bigquery'], 'programming': ['sql']},
 'J-00028807053f': {'analyst_tools': ['excel'], 'cloud': ['oracle']},
 'J-00028974f967': {'programming': ['sql']},
 'J-000298d9940b': {'cloud': ['azure', 'databricks']},
 'J-0002c97f9dd5': {'analyst_tools': ['looker'], 'programming': ['go', 'sql']},
 'J-0002decdaa4a': {'cloud': ['aws', 'azure', 'gcp'],
  'databases': ['cassandra'],
  'libraries': ['airflow', 'hadoop', 'kafka', 'spark'],
  'other': ['flow'],
  'programming': ['c++', 'java', 'nosql', 'python', 'scala', 'sql']},
 'J-0002e020ca4d': {'analyst_tools': ['tableau'], 'programming': ['sql']},
 'J-000315a50f75': {'cloud': ['azure']},
 'J-00031bc67a35': {'analyst_tools': ['power bi', 'tableau'],
  'async': ['jira'],
  'cloud': ['azure', 'snowflake'],
  'databases': ['mysql', 'postgresql', 'sql server'],
  'other': ['git', 'jenkins'],
  'programming': ['java', 'shell', 'sql']},
 'J-00034ca60d17': {'analyst_tools': ['excel',
   'outlook',
   'powerpoint',
   'sas',
   'word'],
  'programming': ['r', 'sas']},
 'J-0003529f8154': {'programming': ['python', 'sql']},
 'J-0003c2cb102c': {'cloud': ['azure'],
  'libraries': ['airflow', 'hadoop', 'kafka', 'spark'],
  'programming': ['java', 'python', 'scala', 'sql']},
 'J-0003e1d82f3b': {'programming': ['sql']},
 'J-000402f936be': {'cloud': ['azure', 'databricks'],
  'libraries': ['pyspark', 'spark'],
  'programming': ['python', 'shell', 'sql']},
 'J-00040561a40d': {'programming': ['python', 'r', 'sql']},
 'J-00042488a9bd': {'cloud': ['bigquery', 'redshift'], 'programming': ['sql']},
 'J-00043b0d11e1': {},
 'J-000445e2b302': {'analyst_tools': ['excel', 'power bi', 'tableau'],
  'programming': ['python', 'r', 'sql']},
 'J-00048229ad51': {},
 'J-0004bf0472d0': {'cloud': ['aws', 'azure', 'databricks', 'gcp'],
  'databases': ['cassandra'],
  'libraries': ['hadoop', 'kafka', 'spark'],
  'programming': ['java', 'python', 'scala']},
 'J-0004f4287e5f': {'analyst_tools': ['ssis'],
  'cloud': ['azure'],
  'libraries': ['spark'],
  'programming': ['python', 'scala']},
 'J-000520f627e0': {'programming': ['c', 'java', 'kotlin', 'python']},
 'J-000531c5a4db': {'cloud': ['gcp'],
  'databases': ['mongodb'],
  'libraries': ['airflow', 'kafka', 'spark'],
  'other': ['kubernetes', 'terraform'],
  'programming': ['mongodb', 'nosql', 'python', 'sql']},
 'J-00053cb53ddc': {'analyst_tools': ['power bi'],
  'cloud': ['azure', 'databricks'],
  'programming': ['go', 'sql']},
 'J-000540688a0a': {'analyst_tools': ['excel', 'power bi'],
  'programming': ['python', 'r', 'sql']},
 'J-000542238c98': {},
 'J-00054649edaa': {'sync': ['zoom']},
 'J-00056299234f': {},
 'J-00056882a390': {'programming': ['python', 'r']},
 'J-00056e8313f7': {'programming': ['sql']},
 'J-00059a55eb4f': {'programming': ['css', 'html', 'javascript']},
 'J-0005a732ec46': {'analyst_tools': ['excel', 'sharepoint'],
  'programming': ['sql']},
 'J-0005aa30b09b': {'analyst_tools': ['power bi', 'sap']},
 'J-0005c94e1f75': {},
 'J-0005dbb0c860': {'programming': ['python', 'sql']},
 'J-0005e17588e8': {'analyst_tools': ['power bi'],
  'cloud': ['azure', 'databricks'],
  'programming': ['java', 'python', 'sql']},
 'J-000616ced311': {},
 'J-00061dc74389': {'cloud': ['aws', 'azure'], 'os': ['linux', 'windows']},
 'J-00062822f775': {'os': ['unix'],
  'other': ['git'],
  'programming': ['go', 'sql']},
 'J-00063af92447': {'cloud': ['azure'],
  'libraries': ['kafka', 'spark'],
  'programming': ['scala']},
 'J-000696cd9d87': {'cloud': ['aws', 'azure', 'gcp'],
  'libraries': ['pytorch', 'tensorflow'],
  'programming': ['python']},
 'J-00069d741a8f': {'libraries': ['airflow',
   'pandas',
   'pyspark',
   'pytorch',
   'spark',
   'tensorflow'],
  'other': ['docker', 'kubernetes'],
  'programming': ['python', 'sql']},
 'J-0006dbf375ae': {'databases': ['cassandra', 'redis'],
  'libraries': ['hadoop', 'kafka', 'spark'],
  'other': ['docker', 'git', 'jenkins', 'kubernetes'],
  'programming': ['go', 'java', 'nosql', 'python', 'scala']},
 'J-0006ec041d78': {'analyst_tools': ['tableau'],
  'cloud': ['aws', 'azure'],
  'databases': ['mongodb'],
  'other': ['git'],
  'programming': ['c#', 'java', 'javascript', 'mongodb']},
 'J-000701d063ae': {'async': ['jira'],
  'libraries': ['airflow', 'pandas'],
  'other': ['bitbucket', 'git', 'jenkins'],
  'programming': ['python', 'sql']},
 'J-000714e5b148': {},
 'J-00074bc3014c': {},
 'J-0007532ef094': {'programming': ['javascript', 'typescript']},
 'J-0007550c2194': {'analyst_tools': ['excel', 'sas', 'spss', 'tableau'],
  'cloud': ['aws', 'azure'],
  'databases': ['sql server'],
  'libraries': ['hadoop', 'spark'],
  'other': ['flow'],
  'programming': ['go', 'sas', 'sql']},
 'J-0007603c734d': {},
 'J-0007758cbac8': {'analyst_tools': ['excel', 'sap']},
 'J-0007a2a29e18': {'cloud': ['aws', 'azure', 'databricks', 'gcp'],
  'libraries': ['pyspark'],
  'programming': ['python']},
 'J-0007a7378dfe': {'analyst_tools': ['dax', 'power bi'],
  'cloud': ['azure'],
  'databases': ['sql server'],
  'programming': ['sql']},
 'J-0007afc63d2d': {'analyst_tools': ['ssrs'],
  'databases': ['sql server'],
  'programming': ['python', 'sql', 't-sql']},
 'J-0007be352b90': {'cloud': ['azure'], 'programming': ['python', 'r']},
 'J-0007c6bd9bd2': {'analyst_tools': ['sas'], 'programming': ['sas']},
 'J-0007cf791b66': {'analyst_tools': ['power bi', 'tableau'],
  'cloud': ['aws'],
  'libraries': ['hadoop'],
  'programming': ['matlab', 'python', 'r']},
 'J-0007d610af19': {'analyst_tools': ['power bi'],
  'cloud': ['aws', 'azure', 'databricks', 'redshift'],
  'libraries': ['pyspark'],
  'programming': ['python', 'sql'],
  'webframeworks': ['express']},
 'J-0007d6378f2c': {'libraries': ['airflow'],
  'other': ['flow'],
  'programming': ['python', 'sql']},
 'J-0007d64cb816': {'cloud': ['azure', 'databricks'],
  'libraries': ['pyspark'],
  'programming': ['python', 'sql']},
 'J-0007dabefe2b': {'cloud': ['aws'],
  'other': ['docker'],
  'programming': ['python', 'sql']},
 'J-0007dc519f05': {'analyst_tools': ['power bi'],
  'cloud': ['azure'],
  'libraries': ['spring'],
  'programming': ['python', 'r']},
 'J-000806888e4b': {'analyst_tools': ['tableau'],
  'programming': ['python', 'sql']},
 'J-00081dec0e09': {'async': ['jira'],
  'databases': ['neo4j'],
  'libraries': ['hadoop'],
  'other': ['git', 'svn'],
  'programming': ['python', 'r']},
 'J-0008386e6ae5': {'cloud': ['aws', 'azure', 'ibm cloud'],
  'libraries': ['hadoop', 'kafka', 'spark']},
 'J-000859ee03ed': {'programming': ['c++', 'go', 'rust'],
  'sync': ['zoom'],
  'webframeworks': ['node']},
 'J-00086aff77bd': {'programming': ['python']},
 'J-00086c7e903c': {'cloud': ['aws', 'azure', 'gcp', 'redshift', 'snowflake'],
  'libraries': ['hadoop', 'spark'],
  'programming': ['go', 'java', 'python', 'scala', 'sql']},
 'J-00087eae1806': {},
 'J-00087f1f6e9a': {'cloud': ['azure'],
  'libraries': ['spark'],
  'programming': ['python', 'r', 'sql']},
 'J-000885f12887': {'libraries': ['spark'],
  'other': ['flow', 'git'],
  'programming': ['scala']},
 'J-000887a59871': {},
 'J-000889bc0686': {'analyst_tools': ['excel', 'power bi'],
  'databases': ['sql server'],
  'other': ['flow'],
  'programming': ['sql', 'visual basic']},
 'J-0008964904c1': {'cloud': ['aws', 'azure', 'gcp'],
  'libraries': ['hugging face',
   'keras',
   'pyspark',
   'pytorch',
   'spark',
   'tensorflow'],
  'programming': ['nosql', 'python', 'r', 'sql']},
 'J-0008b20acb12': {},
 'J-0008b884af94': {'cloud': ['aws',
   'azure',
   'bigquery',
   'databricks',
   'gcp',
   'redshift'],
  'libraries': ['kafka'],
  'programming': ['python']},
 'J-0008c341b574': {'analyst_tools': ['alteryx',
   'excel',
   'power bi',
   'powerpoint',
   'tableau'],
  'async': ['jira'],
  'databases': ['sql server'],
  'programming': ['go', 'sql', 't-sql']},
 'J-0008e0fb5e08': {},
 'J-0008f60600d5': {'analyst_tools': ['sap', 'tableau'],
  'cloud': ['oracle'],
  'programming': ['c', 'html']},
 'J-0008f817898f': {'other': ['flow']},
 'J-0009003d6d27': {'libraries': ['spark'],
  'programming': ['python', 'r', 'sql']},
 'J-0009183e6421': {'cloud': ['aws', 'azure'],
  'other': ['git'],
  'programming': ['go', 'python']},
 'J-00091e28b2c3': {'analyst_tools': ['sap'],
  'cloud': ['oracle'],
  'libraries': ['hadoop', 'spark'],
  'os': ['unix'],
  'programming': ['java', 'python', 'scala', 'shell', 'sql']},
 'J-0009487ff9e1': {'analyst_tools': ['excel', 'tableau'],
  'programming': ['python', 'sql']},
 'J-0009538f671c': {'analyst_tools': ['looker', 'power bi', 'tableau'],
  'cloud': ['aws', 'azure', 'bigquery', 'databricks', 'gcp'],
  'libraries': ['airflow', 'kafka'],
  'other': ['github', 'terraform'],
  'programming': ['python', 'sql']},
 'J-0009aa21bc33': {'programming': ['nosql']},
 'J-0009e5164c15': {'analyst_tools': ['excel']},
 'J-0009ec08e426': {'cloud': ['aws', 'azure', 'databricks'],
  'libraries': ['hadoop', 'spark'],
  'other': ['docker', 'kubernetes'],
  'programming': ['python'],
  'webframeworks': ['django', 'flask']},
 'J-000a090c0a0a': {'databases': ['mongodb'],
  'libraries': ['numpy', 'pandas', 'spark'],
  'os': ['windows'],
  'other': ['jenkins', 'kubernetes'],
  'programming': ['mongodb', 'nosql', 'python', 'sql']},
 'J-000a41f7ff2e': {'cloud': ['aws', 'snowflake']},
 'J-000a52b69d06': {'programming': ['python', 'r', 'sql']},
 'J-000a5dc8c004': {'analyst_tools': ['excel',
   'power bi',
   'powerpoint',
   'word'],
  'programming': ['crystal', 'python']},
 'J-000a679c0db7': {'analyst_tools': ['excel', 'sas', 'spss'],
  'cloud': ['aws', 'azure', 'gcp'],
  'libraries': ['spark'],
  'os': ['linux', 'windows'],
  'other': ['docker', 'jenkins', 'kubernetes'],
  'programming': ['matlab', 'nosql', 'r', 'sas', 'sql'],
  'webframeworks': ['phoenix']},
 'J-000a94e358df': {'analyst_tools': ['looker', 'tableau'],
  'programming': ['python', 'r', 'sql']},
 'J-000ab76bf6f1': {'cloud': ['aws'],
  'databases': ['redis', 'sql server'],
  'other': ['ansible', 'git', 'github', 'jenkins', 'terraform'],
  'programming': ['mongo', 'sql']},
 'J-000abfb84e75': {'libraries': ['hadoop'],
  'other': ['git'],
  'programming': ['python', 'r', 'scala']},
 'J-000ad04e2283': {'databases': ['dynamodb', 'postgresql'],
  'libraries': ['numpy', 'pandas', 'plotly', 'pytorch']},
 'J-000aeba4e144': {'programming': ['go', 'python', 'r']},
 'J-000af4efa3c6': {'programming': ['c#', 'python', 'r', 't-sql']},
 'J-000afbd7d3ee': {},
 'J-000b2f684e48': {},
 'J-000b3d951ed2': {'programming': ['python']},
 'J-000b413fdce8': {'analyst_tools': ['power bi']},
 'J-000b596ab5b1': {'analyst_tools': ['looker', 'power bi'],
  'programming': ['sql']},
 'J-000b672d6e8c': {'libraries': ['hadoop']},
 'J-000b67a736e8': {'libraries': ['gdpr'], 'programming': ['java', 'python']},
 'J-000b752ee9c6': {},
 'J-000b782fc972': {'cloud': ['azure']},
 'J-000b9621e653': {'cloud': ['azure'],
  'databases': ['postgresql', 'sql server'],
  'libraries': ['hadoop', 'spark'],
  'programming': ['nosql', 'python', 'sql']},
 'J-000bd1e11599': {'libraries': ['numpy', 'pandas', 'pytorch'],
  'programming': ['python']},
 'J-000bda4512e1': {},
 'J-000be588005b': {'analyst_tools': ['looker', 'tableau'],
  'programming': ['go', 'sql']},
 'J-000c0a53cd04': {'cloud': ['bigquery'],
  'libraries': ['tensorflow'],
  'other': ['docker'],
  'programming': ['python', 'sql']},
 'J-000c111b84a1': {'cloud': ['azure', 'databricks'],
  'databases': ['sql server'],
  'programming': ['sql']},
 'J-000c4c7e1b25': {'cloud': ['aws'], 'other': ['terraform']},
 'J-000c5b64de46': {'cloud': ['azure', 'databricks'],
  'libraries': ['pyspark'],
  'programming': ['python', 'r', 'sql']},
 'J-000c5f05bf4d': {'cloud': ['azure', 'gcp'],
  'other': ['kubernetes', 'terraform'],
  'programming': ['go', 'java']},
 'J-000c87a3c1fc': {'analyst_tools': ['qlik']},
 'J-000c973afc92': {'cloud': ['azure', 'databricks'],
  'libraries': ['spark'],
  'other': ['terraform']},
 'J-000ca8afc01e': {'cloud': ['azure'], 'other': ['github']},
 'J-000ca8c8f543': {'analyst_tools': ['qlik'],
  'async': ['jira'],
  'cloud': ['bigquery', 'gcp'],
  'libraries': ['pandas'],
  'other': ['gitlab'],
  'programming': ['python', 'sql']},
 'J-000cab9e2c2f': {},
 'J-000cd497d1fe': {'analyst_tools': ['tableau'],
  'programming': ['python', 'r', 'sql']},
 'J-000ce50c7921': {},
 'J-000d13c4561d': {'libraries': ['hadoop', 'kafka', 'spark'],
  'programming': ['java', 'shell', 'sql']},
 'J-000d2ca5fc25': {'analyst_tools': ['power bi', 'tableau'],
  'programming': ['python', 'sql']},
 'J-000d362151e0': {'programming': ['css', 'html', 'javascript']},
 'J-000d4522078d': {'cloud': ['gcp'],
  'libraries': ['hadoop', 'pyspark', 'spark'],
  'os': ['unix']},
 'J-000d58f8fc9d': {'programming': ['python', 'r', 'visual basic']},
 'J-000d600484c7': {'os': ['linux'],
  'other': ['docker', 'git'],
  'programming': ['assembly', 'python']},
 'J-000d6980ac58': {'analyst_tools': ['excel'],
  'libraries': ['hadoop', 'kafka', 'spark'],
  'programming': ['java', 'python', 'r', 'scala', 'sql']},
 'J-000d6b4c7a15': {'programming': ['python', 'sql']},
 'J-000d8536fbf3': {'analyst_tools': ['excel'], 'programming': ['python']},
 'J-000da33a43e4': {'analyst_tools': ['tableau'],
  'cloud': ['aws'],
  'libraries': ['kafka', 'spark'],
  'programming': ['nosql', 'sql']},
 'J-000dc2767db1': {'libraries': ['keras', 'pytorch', 'tensorflow'],
  'programming': ['c++', 'java', 'python']},
 'J-000dcb453eab': {'analyst_tools': ['excel',
   'outlook',
   'powerpoint',
   'visio',
   'word'],
  'programming': ['c']},
 'J-000df511f95b': {},
 'J-000e110a3989': {'cloud': ['azure', 'bigquery'],
  'libraries': ['airflow', 'kafka', 'spark'],
  'other': ['docker', 'flow', 'jenkins', 'kubernetes'],
  'programming': ['f#', 'haskell', 'r', 'scala', 'sql']},
 'J-000e1791322c': {'cloud': ['oracle'],
  'databases': ['postgresql'],
  'programming': ['sql']},
 'J-000e20531f6d': {'analyst_tools': ['sas'],
  'cloud': ['oracle', 'snowflake'],
  'programming': ['python', 'r', 'sas'],
  'webframeworks': ['phoenix']},
 'J-000e332c476d': {'analyst_tools': ['sap']},
 'J-000e422b638e': {'cloud': ['oracle'],
  'databases': ['cassandra', 'mongodb', 'mysql', 'postgresql'],
  'other': ['flow'],
  'programming': ['mongodb', 'nosql', 'python', 'sql']},
 'J-000e457e0e00': {'analyst_tools': ['power bi'], 'programming': ['sql']},
 'J-000e8c114ca1': {'analyst_tools': ['looker', 'power bi', 'tableau'],
  'cloud': ['aws', 'azure', 'gcp'],
  'programming': ['python', 'sql']},
 'J-000e9a7cfb6f': {'analyst_tools': ['power bi', 'tableau', 'word'],
  'cloud': ['aws'],
  'programming': ['python', 'r', 'sql']},
 'J-000eac39f5c4': {'analyst_tools': ['ssis'], 'programming': ['c#', 'sql']},
 'J-000ec8dd693e': {'analyst_tools': ['power bi', 'sas', 'tableau'],
  'cloud': ['azure', 'databricks', 'gcp'],
  'libraries': ['kafka'],
  'os': ['linux'],
  'other': ['github', 'yarn'],
  'programming': ['python', 'r', 'sas', 'sql']},
 'J-000ed82c88a7': {'analyst_tools': ['excel', 'powerpoint', 'sas', 'tableau'],
  'programming': ['r', 'sas']},
 'J-000ee1200f38': {},
 'J-000ee3fda5d7': {'analyst_tools': ['sas'], 'programming': ['sas', 'sql']},
 'J-000f0cc1692e': {'libraries': ['matplotlib',
   'numpy',
   'pandas',
   'plotly',
   'scikit-learn',
   'seaborn'],
  'other': ['git'],
  'programming': ['c', 'sql']},
 'J-000f110a91f7': {'analyst_tools': ['sharepoint']},
 'J-000f2543bb98': {'cloud': ['azure'],
  'libraries': ['spark', 'tensorflow'],
  'programming': ['python', 'r', 'sql']},
 'J-000f292d7fb5': {'analyst_tools': ['power bi', 'tableau'],
  'cloud': ['oracle'],
  'databases': ['couchbase', 'sql server'],
  'programming': ['nosql', 'python', 'shell', 'sql']},
 'J-000f2d4c6f6d': {'cloud': ['aws'],
  'other': ['kubernetes', 'terraform'],
  'programming': ['python', 'sql']},
 'J-000f4eb055cb': {},
 'J-000f4f302391': {'cloud': ['oracle'],
  'databases': ['cassandra', 'sql server'],
  'libraries': ['hadoop', 'kafka', 'spark'],
  'other': ['git', 'jenkins', 'kubernetes'],
  'programming': ['c++', 'java', 'python', 'scala', 'sql']},
 'J-000f5565d2cd': {'cloud': ['aws', 'azure'],

In [16]:
#Map Merged Values Back

df['job_skills'] = df['job_id'].map(merged_skills)
df['job_via'] = df['job_id'].map(merged_via)
df['salary_rate'] = df['job_id'].map(merged_rate)
df['job_type_skills'] = df['job_id'].map(merged_job_type_skills)

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_id
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",[Work Nearby],Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,[],{},J-e02c886264ce
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",[BeBee México],Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"[nosql, power bi, python, r, sql, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",J-64833455be38
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",[LinkedIn],Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"[airflow, azure, c#, dax, docker, jenkins, kub...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",J-c8afb754b830
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",[Diversity.com],Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"[aws, c++, java, keras, matlab, python, pytorc...","{'cloud': ['aws'], 'libraries': ['keras', 'pyt...",J-6b595ba75824
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",[Clearance Jobs],Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"[ansible, aws, bash, git, gitlab, jenkins, ora...","{'cloud': ['aws', 'oracle'], 'other': ['ansibl...",J-88bb30c3cf7d

In [17]:
# Keep only one row per unique job_id
df = df.drop_duplicates(subset='job_id')

In [18]:
# Confirming no job_id duplicates
df[df['job_id'].duplicated()]

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills, job_id]
Index: []

## 2. Skills_df creation

In [19]:
# Select only required columns to reduce memory usage and improve clarity
df_temp = df[['job_id', 'job_title_short', 'job_type_skills']].copy()

# Convert dictionary column into list of (category, skills_list) tuples
# Example: {"programming": ["python", "sql"]} → [("programming", ["python", "sql"])]
# If value is not a dict (e.g., NaN), replace with empty list to avoid errors
df_temp['items'] = df_temp['job_type_skills'].apply(
        lambda d: list(d.items()) if isinstance(d, dict) else []
)

df_temp

,job_id,job_title_short,job_type_skills,items
0,J-e02c886264ce,Senior Data Engineer,{},[]
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","[(analyst_tools, [power bi, tableau]), (progra..."
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","[(analyst_tools, [dax]), (cloud, [azure]), (li..."
3,J-6b595ba75824,Data Engineer,"{'cloud': ['aws'], 'libraries': ['keras', 'pyt...","[(cloud, [aws]), (libraries, [keras, pytorch, ..."
4,J-88bb30c3cf7d,Data Engineer,"{'cloud': ['aws', 'oracle'], 'other': ['ansibl...","[(cloud, [aws, oracle]), (other, [ansible, git..."
...,...,...,...,...
785736,J-354304ecc344,Software Engineer,"{'os': ['linux', 'unix'], 'other': ['ansible',...","[(os, [linux, unix]), (other, [ansible, docker..."
785737,J-8fc5a53a787e,Data Analyst,"{'analyst_tools': ['excel', 'sas'], 'programmi...","[(analyst_tools, [excel, sas]), (programming, ..."
785738,J-03cf31bd4b96,Business Analyst,"{'analyst_tools': ['excel', 'powerpoint']}","[(analyst_tools, [excel, powerpoint])]"
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","[(cloud, [aws, azure, redshift, snowflake]), (..."
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","[(cloud, [aws]), (other, [flow])]"

In [20]:
# Explode list so each row contains one (category, skills_list) pair
df_temp = df_temp.explode('items')
df_temp

,job_id,job_title_short,job_type_skills,items
0,J-e02c886264ce,Senior Data Engineer,{},NaN
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(analyst_tools, [power bi, tableau])"
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(programming, [nosql, python, r, sql])"
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","(analyst_tools, [dax])"
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","(cloud, [azure])"
...,...,...,...,...
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(libraries, [hadoop, kafka, spark])"
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(other, [docker, kubernetes])"
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(programming, [go, mongo, nosql, python, shell..."
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(cloud, [aws])"
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(other, [flow])"

In [21]:
# Remove rows where items is null (i.e., no skills data available)
df_temp = df_temp.dropna(subset=['items'])

# Create explicit copy to avoid SettingWithCopyWarning before assignment
df_temp = df_temp.copy()

# Split tuple into two separate columns: category and skills (list)
df_temp[['category', 'skills']] = pd.DataFrame(
        df_temp['items'].tolist(),
        index=df_temp.index
    )

df_temp

,job_id,job_title_short,job_type_skills,items,category,skills
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(analyst_tools, [power bi, tableau])",analyst_tools,"[power bi, tableau]"
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(programming, [nosql, python, r, sql])",programming,"[nosql, python, r, sql]"
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","(analyst_tools, [dax])",analyst_tools,[dax]
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","(cloud, [azure])",cloud,[azure]
2,J-c8afb754b830,Data Engineer,"{'analyst_tools': ['dax'], 'cloud': ['azure'],...","(libraries, [airflow])",libraries,[airflow]
...,...,...,...,...,...,...
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(libraries, [hadoop, kafka, spark])",libraries,"[hadoop, kafka, spark]"
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(other, [docker, kubernetes])",other,"[docker, kubernetes]"
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(programming, [go, mongo, nosql, python, shell...",programming,"[go, mongo, nosql, python, shell, sql]"
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(cloud, [aws])",cloud,[aws]
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(other, [flow])",other,[flow]

In [22]:
# Explode skills list so each row contains a single skill
# Also drop null values that may exist inside lists
df_temp = df_temp.explode('skills').dropna(subset=['skills'])

# Clean skill names by removing leading/trailing whitespace and Standardize skill names
df_temp['skills'] = df_temp['skills'].str.strip().str.lower()
df_temp

,job_id,job_title_short,job_type_skills,items,category,skills
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(analyst_tools, [power bi, tableau])",analyst_tools,power bi
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(analyst_tools, [power bi, tableau])",analyst_tools,tableau
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(programming, [nosql, python, r, sql])",programming,nosql
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(programming, [nosql, python, r, sql])",programming,python
1,J-64833455be38,Data Analyst,"{'analyst_tools': ['power bi', 'tableau'], 'pr...","(programming, [nosql, python, r, sql])",programming,r
...,...,...,...,...,...,...
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(programming, [go, mongo, nosql, python, shell...",programming,python
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(programming, [go, mongo, nosql, python, shell...",programming,shell
785739,J-a94d273e8878,Data Engineer,"{'cloud': ['aws', 'azure', 'redshift', 'snowfl...","(programming, [go, mongo, nosql, python, shell...",programming,sql
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(cloud, [aws])",cloud,aws
785740,J-03b27285205d,Software Engineer,"{'cloud': ['aws'], 'other': ['flow']}","(other, [flow])",other,flow

In [23]:
# Select final columns and rename for clarity
skills_df = df_temp[
    ['job_id', 'job_title_short', 'category', 'skills']
].rename(columns={'skills': 'skill'})

# Remove duplicate (job_id, skill) combinations
# Ensures same skill is not counted multiple times for a job
skills_df = skills_df.drop_duplicates(subset=['job_id', 'skill'])

skills_df

                job_id    job_title_short       category     skill
1       J-64833455be38       Data Analyst  analyst_tools  power bi
1       J-64833455be38       Data Analyst  analyst_tools   tableau
1       J-64833455be38       Data Analyst    programming     nosql
1       J-64833455be38       Data Analyst    programming    python
1       J-64833455be38       Data Analyst    programming         r
...                ...                ...            ...       ...
785739  J-a94d273e8878      Data Engineer    programming    python
785739  J-a94d273e8878      Data Engineer    programming     shell
785739  J-a94d273e8878      Data Engineer    programming       sql
785740  J-03b27285205d  Software Engineer          cloud       aws
785740  J-03b27285205d  Software Engineer          other      flow

[3593147 rows x 4 columns]